### ISSUE TITLE
RPC error on 0.0.5, unable to rollback to 0.0.3 or 0.0.4

### ISSUE THREAD

**Issue by gonzalonunez** [e2b-dev/code-interpreter#16]
Currently running into this error using `"@e2b/code-interpreter": "^0.0.5"`:

```
RPC Error (-32000): error reading file '/root/.jupyter/kernel_id': open /root/.jupyter/kernel_id: no such file or directory
```

This is the code I'm using to create a new Sandbox that's hitting the error:

 ```
   const newSandbox = await CodeInterpreter.create({
      apiKey: process.env.E2B_API_KEY,
      metadata: {
        session_id: this.sessionID,
      },
    });
```

If I roll back to an earlier version i.e: `0.0.3` or `0.0.4`, I get a different error about not being able to instantiate a Sandbox directly.

**Comment by ValentaTomas** [comment]
Hey @gonzalonunez, we are checking this 👌

**Comment by jakubno** [comment]
@gonzalonunez can you check again, there was a problem with a build, but it should be working now

**Comment by gonzalonunez** [comment]
@ValentaTomas awesome thanks! Let me know if I can help with anything at all 🙏

**Comment by gonzalonunez** [comment]
All set now, it looks like. Thanks!
