### ISSUE TITLE
No matching distribution found for e2b_code_interpreter

### ISSUE THREAD

**Issue by shaggy2626** [e2b-dev/code-interpreter#2]
pip install e2b_code_interpreter
ERROR: Could not find a version that satisfies the requirement e2b_code_interpreter (from versions: none)
ERROR: No matching distribution found for e2b_code_interpreter

**Comment by mlejva** [comment]
The package hasn't been released yet

**Comment by mlejva** [comment]
E2B by itself is just a sandbox. It's general purpose. You can have your agent building coding projects in Typescript in it for example.

This package is using the sandbox and the core sandbox API specifically for the code interpreter use case as you may know from ChatGPT. It has a full Jupyter server running in the background. More details on how this differs is explained in this original PR https://github.com/e2b-dev/E2B/pull/346


> is there anyway to install it without using PIP?
Why do you want a different way for installation than pip?

**Comment by shaggy2626** [comment]
thanks. im trying to set up code interpreter with typingminds https://docs.typingmind.com/plugins/build-a-typingmind-plugin do you know which method would be the best to do?

**Comment by mlejva** [comment]
I'm not familiar with Typingmind but it seems you can add functionality with JavaScript to it. We have JavaScript SDK.

You can install an early/experimental version of this package with `npm` if that helps
```
npm install e2b@0.12.6-stateful-code-interpreter.8
```

**Comment by shaggy2626** [comment]
correct me if im wrong, but the new version kind of mimics the native chatgpt interpreter right? Stateful code interpreter

**Comment by mlejva** [comment]
Yes. We give you the cloud environment where you can let your LLM run code the same way as ChatGPT is using the code interpreter.

You can use any LLM and framework.

**Comment by shaggy2626** [comment]
Is this still the latest one to use? ```npm install e2b@0.12.6-stateful-code-interpreter.8```

**Comment by mlejva** [comment]
Correct. We haven't released this package yet. Finishing the last touches.

Are you asking because of missing any issue or a missing feature?

**Comment by im-calvin** [comment]
What's the timeline on releasing the package? I want to test out some of the features like plotting graphs but it seems that the `CodeInterpreter` from `e2b` doesn't contain the method `.notebook` and I can't import from `@e2b/code-intepreter` because the package isn't released yet.

**Comment by mlejva** [comment]
Hi @im-calvin , we're aiming for an official release in 1 week. We could do pre-release for early users like you.

What do you think @jakubno?

**Comment by im-calvin** [comment]
An early release would be great. I'm just working on a code interpreter similar to the OpenAI playground one. The source code is here if you were interested https://github.com/im-calvin/openai-playground

**Comment by im-calvin** [comment]
JS!

**Comment by ValentaTomas** [comment]
Hey @im-calvin, we created a prerelease that you can try right now.

Install with `npm i @e2b/code-interpreter@0.0.1-rc.0`.
