### ISSUE TITLE
Great work!! Keep it up

### ISSUE THREAD

**Issue by artknight** [e2b-dev/code-interpreter#35]
Hey, I wasn’t sure how to reach you, so I’m posting here. I love your work and decided to feature your library in my daily tech newsletter, https://dailysandbox.com

**Comment by ValentaTomas** [comment]
Thank you @artknight!

We have a [Discord](https://discord.com/invite/U7KEcGErtQ) and [X/Twitter](https://x.com/e2b_dev) if you want to reach out more directly.
