### ISSUE TITLE
Error downloading file from sandbox

### ISSUE THREAD

**Issue by dominpm** [e2b-dev/code-interpreter#49]
When trying to download a file from the sandbox like this:

file : str = "path/to/file/in/sandbox/"
content_file = sandbox.files.read(file)
with open(local_file_path, 'wb') as f:
    f.write(content_file)

I get an error that specifies: 
                  a bytes-like object is required, not 'str'

Meaning that content_file i.e. the output of sandbox.files.read() is a string, instead of a bytes-like object as the documentations treats it like.

**Comment by mlejva** [comment]
Sorry about this, we fixed the docs. Thanks for letting us know.
