### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by raivatshah** [e2b-dev/code-interpreter#6]
Hi folks, 

Thanks so much for creating this repo! I'm curious if any of you have tried it with typescript and if there are plans to add types in the future? Would really love to have typescript support! 

Cheers!

**Comment by jakubno** [comment]
Hi @raivatshah, 

code interpreter is written in Python and Typescript. You can find the typescript version [here](https://github.com/e2b-dev/code-interpreter/tree/main/js).
