### ISSUE TITLE
CodeInterpreter.reconnect() not working as expected

### ISSUE THREAD

**Issue by im-calvin** [e2b-dev/code-interpreter#7]
I ran into this issue and am extremely confused, is this a problem on my end or through the library

![image](https://github.com/e2b-dev/code-interpreter/assets/61614687/f355d1f5-f4b7-4e70-991d-5d8194ded0e9)

**Comment by mlejva** [comment]
Can you show the collapsed frames?
<img width="235" alt="Screenshot 2024-04-08 at 1 02 15 PM" src="https://github.com/e2b-dev/code-interpreter/assets/5136688/fd49f76d-fbae-4382-a590-819b9e548fb9">

**Comment by mlejva** [comment]
One more thing @im-calvin , can you add `console.log(sandboxId)` to make sure `sandboxId` is not undefined?
