### ISSUE TITLE
should changesets deps be dev deps?

### ISSUE THREAD

**Issue by transitive-bullshit** [e2b-dev/code-interpreter#8]
![CleanShot 2024-04-08 at 15 32 16@2x](https://github.com/e2b-dev/code-interpreter/assets/552829/fce53335-1854-49b5-9cd9-3914c7e8564a)

(first thing I do when checking out new projects is sanity check their deps)

Overall, projects looks really awesome – excited to play around with it 💪

**Comment by mlejva** [comment]
Thanks for catching this @transitive-bullshit! Fixed now.
